on: pull_request
name: Test

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Clone repository and checkout branch
      - uses: actions/setup-node@v2
        name: Setup node.js
        with:
          node-version: 16
      - run: rm -r .npmrc
        name: Remove .npmrc for the test run
      - run: yarn
        name: Install dependencies
      - run: yarn test
        name: Run tests