on: pull_request
name: Test

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Clone repository and checkout branch
      - uses: actions/setup-node@v2
        name: Setup node.js
        with:
          node-version: 16
      - run: yarn
        name: Install dependencies
      - run: npm run test:core
        name: yarn test